services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports: ["6333:6333","6334:6334"]
    restart: unless-stopped

  embedchat:
    image: sentinel-embed-chat:latest
    build: ./educhat-embed-chat/app
    container_name: embedchat
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=sentinel_docs
    depends_on: [qdrant]
    stdin_open: true
    tty: true
    command: ["bash","-lc","python educhat_agent.py"]

  alertsapi:
    image: sentinel-alerts-api:latest
    build: ./educhat-embed-chat/app
    container_name: alertsapi
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - QDRANT_URL=http://qdrant:6333
      - QDRANT_COLLECTION=sentinel_docs
    depends_on: [qdrant]
    ports: ["8080:8080"]
volumes:
  qdrant_storage: